version: "3.8"

services:
  mysql-gimnasio:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clave123
      MYSQL_DATABASE: gimnasio
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306" # ajuste el puerto del host si es necesario

  backend-gimnasio:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_DSN: "root:clave123@tcp(mysql-gimnasio:3306)/gimnasio?charset=utf8mb4&parseTime=True&loc=Local"
    depends_on:
      - mysql-gimnasio

  frontend-gimnasio:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env

volumes:
  mysql_data:
